DROP TABLE SCHOOL;
DROP TABLE STUDENT;

CREATE TABLE SCHOOL
(
SCHOOL_CODE NUMBER(10) PRIMARY KEY,
SCHOOL_NAME VARCHAR2(10),
SCHOOL_ADDRESS VARCHAR2(40)
);

CREATE TABLE STUDENT
(
STUDENT_ID NUMBER(10) PRIMARY KEY,
STUDENT_NAME VARCHAR2(20),
SCHOOL_CODE NUMBER(10),
CONSTRAINT STUDENT_SCHOOL_CODE_FK FOREIGN KEY (SCHOOL_CODE)
REFERENCES SCHOOL(SCHOOL_CODE) ON DELETE CASCADE
);

INSERT INTO SCHOOL
VALUES(100,'ENG','DENVER');

INSERT INTO SCHOOL
VALUES(200,'SCI','AURORA');

INSERT INTO STUDENT
VALUES(123,'MIKE',100);

INSERT INTO STUDENT
VALUES(345,'JOHN',100);

INSERT INTO STUDENT
VALUES(567,'DAVID',100);

INSERT INTO STUDENT
VALUES(789,'ALLEN',200);

INSERT INTO STUDENT
VALUES(890,'WILLIAM',200);

COMMIT;

SELECT * FROM SCHOOL;
SELECT * FROM STUDENT;

